drop table if exists member CASCADE;
create table board
(
    board_no bigint generated by default as identity,
    tittle varchar(20) not null,
    content varchar(200) not null,
    name varchar(20) not null,
    created_ts timestamp default CURRENT_TIMESTAMP,
    updated_ts timestamp,
    deleted_ts timestamp,
    is_deleted tinyint(1),

    primary key (board_no)
);