drop table if exists member CASCADE;
create table member
(
    user_no bigint generated by default as identity,
    id varchar(30) not null,
    pw varchar(30) not null,
    name varchar(10) not null,
    birthdate varchar(30) not null,
    sex varchar(5) not null,
    phone varchar(15) not null,
    created_ts timestamp default CURRENT_TIMESTAMP not null,
    updated_ts timestamp,
    deleted_ts timestamp,
    is_deleted tinyint(1),

    primary key (user_no)
);